version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    image: ${DOCKER_USERNAME}/express-prisma-app:latest
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?schema=public
      NODE_ENV: production
    ports:
      - "3000:3000"
    networks:
      - app-network
    command: >
      sh -c "npx prisma migrate deploy && npm start"

volumes:
  postgres_data:

networks:
  app-network: